#!/usr/bin/env python

#ARDUINO
CONST_SERIAL_RPI_INITIALIZED = 48
CONST_SERIAL_RPI_STOP = 49
CONST_SERIAL_RPI_START = 50
CONST_SERIAL_RPI_SPEED = 51
CONST_SERIAL_RPI_DIRECTION = 52
CONST_STATE_MOVEMENT = 70
CONST_STATE_STOP = 71
CONST_STATE_STAIRS = 72
CONST_STATE_OBSTACLE = 73
CONST_OBSTACLE_SWITCHES = 74
CONST_OBSTACLE_SONAR_FRONT = 75
CONST_OBSTACLE_SONAR_BACK = 76
CONST_FLOOR = 77
CONST_LIMIT = 78
CONST_MPU = 79

#CONTROL

#STATE
